apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-net
spec:
  rules:
    - host: gos.my.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-web
                port:
                  number: 80

