apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rustfs-page
  namespace: s3
spec:
  rules:
    - host: s3.gos.my.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rustfs
                port:
                  number: 9000
          - path: /rustfs/console
            pathType: Prefix
            backend:
              service:
                name: rustfs
                port:
                  number: 9001
